var webTitle = "Mundocero - SensePi Project";
var webHeader = "SensePi - Aplicaciones Web";
var arduinoRasPiHeader = "Sensores Arduino & Raspberry Pi board";
var navHome = "Inicio";
var navTeam = "Equipo";
var navDetails = "Detalles";
var navLog = "Bitácora";
var navLogIn = "Iniciar sesión";
var navContact = "Contacto";
var logInButtonText = "Iniciar sesión";
var SignUpButtonText = "Registrarse";
var yesAccountMessage = "Ya tienes una cuenta?"
var noAccountMessage = "Todavía no tienes cuenta?"
var logInNowButtonText = "Inicia sesión ahora";
var SignUpNowButtonText = "Regístrate ahora";
var NewNickText = "Introduce tu nick deseado:";
var NickText = "Nick";
var NewEmailText = "Introduce tu email:";
var EmailText = "Email";
var NewPasswordText = "Introduce tu nuevo contraseña:";
var PasswordText = "Contraseña";
var ConfirmPasswordText = "Confirma tu contraseña";
var loginSuccess = "Correcto! Uniéndote...";
var loginFail1 = "Usuario y/o email y/o contraseña incorrectos. Inténtalo de nuevo.";
var loginFail2 = "Incorrecto. ¡Esta vez, da lo mejor de ti!";
var loginFail3 = "Incorrecto. ¿Eres tú de verdad?";
var signUpSuccess = "Acabas de unirte a nosotros! Comprueba tu email para la verificación.";
var signUpFail =  "El nick y/o email ya existen.";
var signUpWrongPassword =  "La contraseña no coincide con la contraseña confirmada.";
var signUpWrongEmail =  "La dirección de email no es válida.";
var warningMessageText = "Acceso bloqueado tras 3 intentos fallidos.";
var passwordRecover = "Recupera tu contraseña aquí.";
var footerLink = "SensePi";
var footerSentence = ", un proyecto de alumnos para la FdI";
var evaluation = "Evalución";
var suggest = "Sugerencia"
var review = "Critica"
var texAreaContact = "Queremos leer tu opinión!";
var accordance = "Marque esta casilla para verificar  que ha leído nuestros términos y condiciones del servicio";
